services:
  - type: web
    name: cimore-backend
    env: python
    plan: free
    # Added 'server/' prefix to match your repository structure
    buildCommand: pip install -r server/requirements.txt && python server/manage.py collectstatic --noinput
    # Told gunicorn to look inside the 'server' directory
    startCommand: gunicorn --pythonpath server cimore_backend.wsgi
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"