services:
  - type: web
    name: CiMOReDeploy
    runtime: python
    env: python
    plan: free
    buildCommand: pip install -r server/requirements.txt && python server/manage.py collectstatic --noinput
    startCommand: gunicorn --pythonpath server cimore_backend.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"  # This forces a stable version
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"