# Generated by Django 6.0.4 on 2026-04-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_school_is_archived_alter_marketingrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='Staff', max_length=20),
        ),
    ]
