# Generated by Django 5.2.13 on 2026-05-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('request', 'Request'), ('user', 'User'), ('system', 'System'), ('announcement', 'Announcement'), ('message', 'Message')], default='system', max_length=20),
        ),
    ]
