# Generated by Django 5.2.13 on 2026-05-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_notification_type_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='recipient_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
