# Generated by Django 5.2.13 on 2026-05-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_communication_log_file_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='client_temp_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
