# Generated by Django 6.0.4 on 2026-04-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_marketingrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='last_visited',
            field=models.DateField(blank=True, null=True),
        ),
    ]
